# Generated by Django 3.0.3 on 2020-02-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsm_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AlterField(
            model_name='board',
            name='mac_address_board',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
